apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: production
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: database-1.crwsogqrjx0g.ap-southeast-1.rds.amazonaws.com
        - name: WORDPRESS_DB_USER
          value: admin
        - name: WORDPRESS_DB_PASSWORD
          value: "123456789"
        - name: WORDPRESS_DB_NAME
          value: wordpress_1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: production
spec:
  selector:
    app: wordpress
  ports:
  - port: 8030
    targetPort: 80