apiVersion: v1
kind: ConfigMap
metadata:
  name: p-fb-configmap
  namespace: production
data:
  config.php: |
    <?php
    $db_host = "database-1.crwsogqrjx0g.ap-southeast-1.rds.amazonaws.com";
    $db_user = "admin";
    $db_pass = "123456789";
    $db_name = "database_1";
    try {
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>